SenzaInfo:
    StackName: crate
    Parameters:
        - DockerImage:
            Description: "stups-crate DockerImage to use, including image tag (e.g. pierone.stups.example.org/team/stups-crate:0.54.6)"
        - ApplicationId:
            Description: "The application id according to yourturn"
        - MintBucket:
            Description: The Mint bucket to use for getting credentials and stuff
        - ClusterName:
            Description: "name of the crate cluster"
        - HeapSize:
            Description: "JVM Heap size for Crate (use half of available RAM but less than 32GB)"
            Default: "4g"
        - ScalyrAccountKey:
            Description: "scalyr account key"
            Default: "NOT USED"
SenzaComponents:
    - Configuration:
        Type: Senza::StupsAutoConfiguration
    - CrateCluster:
        Type: Senza::TaupageAutoScalingGroup
        InstanceType: "c3.2xlarge"
        SecurityGroups:
            - Fn::GetAtt:
                - StupsCrateSg
                - GroupId
        IamRoles:
            - Ref: IamRole
        AutoScaling:
            # we don't really autoscale dynamically
            # add nodes by updating this stack with senza update
            # the autoscaling group will create a new node
            # TODO: make those values settable from parameters (some python/templating error)
            Minimum: 3
            Maximum: 3
            MetricType: CPU
        AssociatePublicIpAddress: false
        TaupageConfig:
            application_id: "{{Arguments.ApplicationId}}"
            runtime: Docker
            networking: host
            source: "{{Arguments.DockerImage}}"
            scalyr_account_key: "{{Arguments.ScalyrAccountKey}}"
            mint_bucket: "{{Arguments.MintBucket}}"
            health_check_port: 9200
            # requires the crate setting es.api.enabled: true
            health_check_path: /_cluster/health
            ports:
                4200: 4200
                4300: 4300
            volumes:
                raid:
                    /dev/md/crate: 
                        level: 0
                        devices:
                            - /dev/xvdb
                            - /dev/xvdc
            mounts:
                /data:
                    partition: /dev/md/crate
                    filesystem: ext4
                    options: noatime,nodiratime,nobarrier
                    erase_on_boot: true
            environment:
                CLUSTER_NAME: "{{Arguments.ClusterName}}"
                CRATE_HEAP_SIZE: "{{Arguments.HeapSize}}"
                AWS_SECURITY_GROUP:
                    Fn::GetAtt:
                        - StupsCrateSg
                        - GroupId
                # TODO calculate this depending on the number of nodes in the cluster,
                # once it is dynamic
                MINIMUM_MASTER_NODES: 2
Resources:
    StupsCrateSg:
        Type: AWS::EC2::SecurityGroup
        Properties:
            GroupDescription: "Crate exposed ports"
            SecurityGroupIngress:
              - IpProtocol: tcp # HTTP
                FromPort: 4200
                ToPort: 4200
                CidrIp: 0.0.0.0/0
              - IpProtocol: tcp # Transport
                FromPort: 4300
                ToPort: 4300
                CidrIp: 0.0.0.0/0
              - IpProtocol: tcp
                FromPort: 22
                ToPort: 22
                CidrIp: 0.0.0.0/0
    IamRole:
      Type: AWS::IAM::Role
      Properties:
        AssumeRolePolicyDocument:
          Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Principal:
                Service: ec2.amazonaws.com
              Action: sts:AssumeRole
        Path: /
        Policies:
          - PolicyName: AmazonS3MintBucketAccess
            PolicyDocument:
              Version: "2012-10-17"
              Statement:
                - Effect: Allow
                  Sid: AllowMintRead
                  Action: s3:GetObject
                  Resource: "arn:aws:s3:::{{Arguments.MintBucket}}/{{Arguments.ApplicationId}}/*"
          - PolicyName: AmazonEC2APIAccess
            PolicyDocument:
              Version: "2012-10-17"
              Statement:
                - Effect: Allow
                  Action:
                    # needed for crate aws discovery
                    - ec2:DescribeInstances
                  Resource: "*"
